site_name: xConnect Documentation
site_url: https://senecaxconnect.github.io/xconnect_docs
site_description: xConnect Documentation
site_author: Seneca

repo_name: 'senecaxconnect/xconnect_docs'
repo_url: 'https://github.com/senecaxconnect/xconnect_docs'

nav:
  - Home: index.md
  - Introduction to xConnect: Platform_Overview.md
  - Getting Started: Getting_Started.md
  - Learn about the platform:
      - Server Agent: Agent_Overview.md
      - Gateway: Gateway_Overview.md
      - Web Dashboard: Dashboard_Overview.md
      - Network Requirements: Network_Requirements.md
  - Guides:
      - Dashboards: Usage_Dashboards.md
      - Bookmarks: Usage_Bookmarks.md
      - User Types: Usage_Roles.md
      - Navigation: Usage_SideNav.md
      - Customer Management: Usage_ManageCustomers.md
      - User Management: Usage_ManageUsers.md
      - Gateway Management: Usage_ManageGateways.md
      - Device Management: Usage_ManageDevices.md
      - Event Configurations: Usage_ManageEventConfigurations.md
      - Email Profiles: Usage_ManageEmailProfiles.md
      - Remote Commands: Usage_ManageRemoteCommands.md
      - 3rd Party Connectors: Usage_ManageConnectors.md
      - Event Logs: Usage_EventLogs.md

  - Developer Documentation:
      - Agent: Agent_API.md
      - Platform:
        - Azure-Based Authentication: Auth_AzureAD.md
        - Genetec Integration: Setup_GenetecIntegration.md
        - API Request Signing: API_RequestSigning.md
  - Get Help: Support.md
  - Release Notes: Release_Notes.md

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  logo: 'images/logo.svg'

plugins:
    - search

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - toc

extra_css:
  # - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/mermaid.css
  - stylesheets/site.css

extra_javascript:
  - https://unpkg.com/mermaid@7.0.9/dist/mermaid.min.js
  #- https://unpkg.com/mermaid@8.4.5/dist/mermaid.min.js
copyright: Copyright &copy; 2022 <a href="https://www.senecadata.com"> - Seneca Data Distributors, Inc</a>
