site_name: xConnect Documentation
site_url: https://senecaxconnect.github.io/xconnect_docs
site_description: xConnect Documentation
site_author: Seneca

repo_name: 'senecaxconnect/xconnect_docs'
repo_url: 'https://github.com/senecaxconnect/xconnect_docs'

nav:
    - Platform:
       - Overview: Platform_Overview.md
       - Server Agent: Agent_Overview.md
       - Gateway: Gateway_Overview.md
       - Web Dashboard: Dashboard_Overview.md
    - Getting Started:
       - Quick Start Guide: Getting_Started.md
       - Step 1 - Gateway Setup:
         - Turnkey Appliance: Gateway_TurnKey.md
         - Virtual/Software/Docker: Gateway_Docker.md
       - Step 2 - Install Agent: Agent_Install.md
       - Step 3 - Web Dashboard: Dashboard_Setup.md
    - Usage Guide:
        - Dashboards: Usage_Dashboards.md
        - Bookmarks: Usage_Bookmarks.md
        - User Types: Usage_Roles.md
        - Management:
            - Customers: Usage_ManageCustomers.md
            - Users: Usage_ManageUsers.md
            - Gateways: Usage_ManageGateways.md
            - Devices: Usage_ManageDevices.md
            - Event Configurations: Usage_ManageEventConfigurations.md
            - Email Profiles: Usage_ManageEmailProfiles.md
            - Remote Commands: Usage_ManageRemoteCommands.md
            - 3rd Party Connectors: Usage_ManageConnectors.md
        - Event Logs: Usage_EventLogs.md
    - Support: Support.md
    - Release Notes: Release_Notes.md


theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  logo: 'images/logo.svg'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@7.0.9/dist/mermaid.min.js
  #- https://unpkg.com/mermaid@8.4.5/dist/mermaid.min.js
copyright: Copyright &copy; 2020 <a href="https://www.senecadata.com"> - Seneca Data Distributors, Inc</a>
